/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Comfy API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import { customInstance } from './mutator/axios-instance'
/**
 * Echo-compatible error response for private feedback and admin scan endpoints. Branch on HTTP status, not the human-readable message. Authentication middleware may add an error field.
 */
export interface FeedbackError {
  message: string
  error?: string
}

export type AdminNodeVersionAllOf = {
  /** Raw scan evidence and internal moderation history. Registry admins only. */
  status_reason: string
}

export type AdminNodeVersion = NodeVersion & AdminNodeVersionAllOf

/**
 * unprocessed: no feedback messages; processed: the latest message is from an admin; needs_response: the latest message is from an author. Only the current Publisher conversation is considered, including resolved or archived conversations.
 */
export type VersionFeedbackStatus =
  (typeof VersionFeedbackStatus)[keyof typeof VersionFeedbackStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VersionFeedbackStatus = {
  unprocessed: 'unprocessed',
  processed: 'processed',
  needs_response: 'needs_response',
} as const

export type FeedbackState = (typeof FeedbackState)[keyof typeof FeedbackState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeedbackState = {
  awaiting_author: 'awaiting_author',
  awaiting_admin: 'awaiting_admin',
  resolved: 'resolved',
} as const

export interface FeedbackThread {
  id: string
  node_id: string
  version_id: string
  version: string
  publisher_id: string
  state: FeedbackState
  revision: number
  last_message_seq: number
  last_message_at: string
  archived: boolean
}

export type FeedbackMessageSenderRole =
  (typeof FeedbackMessageSenderRole)[keyof typeof FeedbackMessageSenderRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeedbackMessageSenderRole = {
  admin: 'admin',
  author: 'author',
} as const

export interface FeedbackMessage {
  id: string
  seq: number
  sender_user_id: string
  sender_name: string
  sender_role: FeedbackMessageSenderRole
  body: string
  created_at: string
}

export type FeedbackEventEventType =
  (typeof FeedbackEventEventType)[keyof typeof FeedbackEventEventType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeedbackEventEventType = {
  resolved: 'resolved',
  reopened: 'reopened',
  archived: 'archived',
  superseded: 'superseded',
} as const

export interface FeedbackEvent {
  id: string
  event_type: FeedbackEventEventType
  /** Replacement nodepack version UUID, present on superseded events. */
  replacement_version_id?: string
  /** Replacement nodepack version number at the time of the handoff. */
  replacement_version?: string
  created_at: string
}

export interface FeedbackPermissions {
  can_start: boolean
  can_reply: boolean
  can_resolve: boolean
  can_reopen: boolean
}

/**
 * Echo the target from the displayed feedback response on every write. A stale Publisher or thread returns 409. A null thread is valid only when starting a conversation or retrying that same first message.
 */
export interface FeedbackWriteTarget {
  /** @minLength 1 */
  publisher_id: string
  /** @nullable */
  thread_id: string | null
}

/**
 * @nullable
 */
export type FeedbackResponseThread = FeedbackThread | null

export interface FeedbackResponse {
  target: FeedbackWriteTarget
  /** @nullable */
  thread: FeedbackResponseThread
  messages: FeedbackMessage[]
  events: FeedbackEvent[]
  permissions: FeedbackPermissions
  unread_count: number
  last_read_message_seq: number
  /** @nullable */
  next_before_seq: number | null
}

export interface FeedbackSummary {
  thread: FeedbackThread
  unread_count: number
}

export interface FeedbackInbox {
  threads: FeedbackSummary[]
  /** @nullable */
  next_cursor: string | null
}

/**
 * UTF-8 Markdown source, limited to 5,000 Unicode code points after trimming. The server stores source text; clients must render it safely.
 */
export interface FeedbackMessageInput {
  target: FeedbackWriteTarget
  /**
   * @minLength 1
   * @maxLength 5000
   */
  body: string
  client_message_id: string
}

export type FeedbackStateInputState =
  (typeof FeedbackStateInputState)[keyof typeof FeedbackStateInputState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeedbackStateInputState = {
  resolved: 'resolved',
  open: 'open',
} as const

/**
 * A conditional state change. Echo target and thread.revision from the conversation you inspected; a stale recipient or revision returns 409.
 */
export interface FeedbackStateInput {
  target: FeedbackWriteTarget
  state: FeedbackStateInputState
  /** @minimum 0 */
  expected_revision: number
}

export interface FeedbackSupersedeInput {
  /**
   * @minItems 1
   * @maxItems 100
   */
  versions: FeedbackSupersedeVersion[]
}

export interface FeedbackSupersedeVersion {
  version_id: string
  target: FeedbackWriteTarget
  /** @minimum 0 */
  expected_revision: number
}

export interface FeedbackReadInput {
  target: FeedbackWriteTarget
  /** @minimum 0 */
  last_read_message_seq: number
}

export interface FeedbackReadResult {
  last_read_message_seq: number
}

export interface AdminVersionList {
  versions: AdminNodeVersion[]
  total: number
  page: number
  pageSize: number
  totalPages: number
}

export interface ErrorResponse {
  error: string
  message: string
}

export interface NodeVersion {
  id?: string
  /** The version identifier, following semantic versioning. Must be unique for the node. */
  version?: string
  /** The date and time the version was created. */
  createdAt?: string
  /** Summary of changes made in this version */
  changelog?: string
  /** A list of pip dependencies required by the node. */
  dependencies?: string[]
  /** [Output Only] URL to download this version of the node */
  downloadUrl?: string
  /** Indicates if this version is deprecated. */
  deprecated?: boolean
  /** The status of the node version. */
  status?: NodeVersionStatus
  /** Public installation information used by Manager policies. Only trusted administrators can write these tags. */
  readonly tags_admin?: readonly string[]
  /** The unique identifier of the node. */
  node_id?: string
}

export type NodeVersionStatus =
  (typeof NodeVersionStatus)[keyof typeof NodeVersionStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeVersionStatus = {
  NodeVersionStatusActive: 'NodeVersionStatusActive',
  NodeVersionStatusDeleted: 'NodeVersionStatusDeleted',
  NodeVersionStatusBanned: 'NodeVersionStatusBanned',
  NodeVersionStatusPending: 'NodeVersionStatusPending',
  NodeVersionStatusFlagged: 'NodeVersionStatusFlagged',
} as const

export type AdminGetVersionFeedbackParams = {
  /**
   * @minimum 1
   */
  before_seq?: number
}

export type AdminListVersionFeedbackParams = {
  /**
   * Exact match. Omit to leave unrestricted; an explicitly empty value matches no conversations.
   */
  nodeId?: string
  /**
   * Exact match. Omit to leave unrestricted; an explicitly empty value matches no conversations.
   */
  publisherId?: string
  state?: FeedbackState
  cursor?: string
}

export type AuthorGetVersionFeedbackParams = {
  /**
   * @minimum 1
   */
  before_seq?: number
}

export type AuthorListVersionFeedbackParams = {
  /**
   * Exact match. Omit to leave unrestricted; an explicitly empty value matches no conversations.
   */
  nodeId?: string
  /**
   * Exact match. Omit to leave unrestricted; an explicitly empty value matches no conversations.
   */
  publisherId?: string
  state?: FeedbackState
  cursor?: string
}

export type AdminListNodeVersionsParams = {
  nodeId?: string
  statuses?: NodeVersionStatus[]
  status_reason?: string
  /**
   * Exact nodepack version number. Applied before pagination; combine with nodeId for a replacement-version link. An explicitly empty value matches no versions.
   */
  version?: string
  /**
   * Filter by the latest feedback message for the current Publisher. Applied before counting and pagination, independently of conversation resolution and version moderation status. Omit to include all versions.
   */
  feedback_status?: VersionFeedbackStatus
  /**
   * @minimum 1
   */
  page?: number
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Uses a Firebase ID token for an active Registry admin. The versionId is a UUID, not the version string. Returns the latest 30 messages in ascending sequence order; follow next_before_seq through before_seq to load older messages. GET never marks messages read. Preserve target for writes, inspect permissions, and use thread.revision for state changes. A null thread still supplies the target needed to start feedback.
 * @summary Read a private version conversation and its allowed actions
 */
export const adminGetVersionFeedback = (
  nodeId: string,
  versionId: string,
  params?: AdminGetVersionFeedbackParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<FeedbackResponse>(
    {
      url: `/admin/nodes/${nodeId}/versions/${versionId}/feedback`,
      method: 'GET',
      params,
      signal,
    },
    options
  )
}

export const getAdminGetVersionFeedbackQueryKey = (
  nodeId?: string,
  versionId?: string,
  params?: AdminGetVersionFeedbackParams
) => {
  return [
    `/admin/nodes/${nodeId}/versions/${versionId}/feedback`,
    ...(params ? [params] : []),
  ] as const
}

export const getAdminGetVersionFeedbackQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetVersionFeedback>>,
  TError = FeedbackError,
>(
  nodeId: string,
  versionId: string,
  params?: AdminGetVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminGetVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getAdminGetVersionFeedbackQueryKey(nodeId, versionId, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminGetVersionFeedback>>
  > = ({ signal }) =>
    adminGetVersionFeedback(nodeId, versionId, params, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!(nodeId && versionId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetVersionFeedback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetVersionFeedbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetVersionFeedback>>
>
export type AdminGetVersionFeedbackQueryError = FeedbackError

export function useAdminGetVersionFeedback<
  TData = Awaited<ReturnType<typeof adminGetVersionFeedback>>,
  TError = FeedbackError,
>(
  nodeId: string,
  versionId: string,
  params: undefined | AdminGetVersionFeedbackParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminGetVersionFeedback>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetVersionFeedback>>,
          TError,
          Awaited<ReturnType<typeof adminGetVersionFeedback>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminGetVersionFeedback<
  TData = Awaited<ReturnType<typeof adminGetVersionFeedback>>,
  TError = FeedbackError,
>(
  nodeId: string,
  versionId: string,
  params?: AdminGetVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminGetVersionFeedback>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetVersionFeedback>>,
          TError,
          Awaited<ReturnType<typeof adminGetVersionFeedback>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminGetVersionFeedback<
  TData = Awaited<ReturnType<typeof adminGetVersionFeedback>>,
  TError = FeedbackError,
>(
  nodeId: string,
  versionId: string,
  params?: AdminGetVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminGetVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Read a private version conversation and its allowed actions
 */

export function useAdminGetVersionFeedback<
  TData = Awaited<ReturnType<typeof adminGetVersionFeedback>>,
  TError = FeedbackError,
>(
  nodeId: string,
  versionId: string,
  params?: AdminGetVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminGetVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAdminGetVersionFeedbackQueryOptions(
    nodeId,
    versionId,
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Send state=resolved to close or state=open to reopen, with the observed target and thread.revision as expected_revision. Reopening derives the awaiting state from the latest sender. This does not approve or reject the node version. On 409, GET and reassess current permissions and state; do not blindly replace expected_revision or the recipient.
 * @summary Resolve or reopen a private conversation
 */
export const adminSetVersionFeedbackState = (
  nodeId: string,
  versionId: string,
  feedbackStateInput: FeedbackStateInput,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<FeedbackResponse>(
    {
      url: `/admin/nodes/${nodeId}/versions/${versionId}/feedback`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: feedbackStateInput,
    },
    options
  )
}

export const getAdminSetVersionFeedbackStateMutationOptions = <
  TError = FeedbackError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminSetVersionFeedbackState>>,
    TError,
    { nodeId: string; versionId: string; data: FeedbackStateInput },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminSetVersionFeedbackState>>,
  TError,
  { nodeId: string; versionId: string; data: FeedbackStateInput },
  TContext
> => {
  const mutationKey = ['adminSetVersionFeedbackState']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminSetVersionFeedbackState>>,
    { nodeId: string; versionId: string; data: FeedbackStateInput }
  > = (props) => {
    const { nodeId, versionId, data } = props ?? {}

    return adminSetVersionFeedbackState(nodeId, versionId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminSetVersionFeedbackStateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminSetVersionFeedbackState>>
>
export type AdminSetVersionFeedbackStateMutationBody = FeedbackStateInput
export type AdminSetVersionFeedbackStateMutationError = FeedbackError

/**
 * @summary Resolve or reopen a private conversation
 */
export const useAdminSetVersionFeedbackState = <
  TError = FeedbackError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminSetVersionFeedbackState>>,
      TError,
      { nodeId: string; versionId: string; data: FeedbackStateInput },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof adminSetVersionFeedbackState>>,
  TError,
  { nodeId: string; versionId: string; data: FeedbackStateInput },
  TContext
> => {
  const mutationOptions =
    getAdminSetVersionFeedbackStateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}

/**
 * Send Markdown source in body and echo target from a fresh conversation response. Generate one client_message_id UUID per logical message and reuse the identical payload when retrying an ambiguous failure. A successful retry does not duplicate the message. Do not retarget a pending message after ownership changes. Returns the updated conversation and permissions.
 * @summary Start or reply to a private version conversation
 */
export const adminSendVersionFeedback = (
  nodeId: string,
  versionId: string,
  feedbackMessageInput: FeedbackMessageInput,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<FeedbackResponse>(
    {
      url: `/admin/nodes/${nodeId}/versions/${versionId}/feedback/messages`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: feedbackMessageInput,
      signal,
    },
    options
  )
}

export const getAdminSendVersionFeedbackMutationOptions = <
  TError = FeedbackError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminSendVersionFeedback>>,
    TError,
    { nodeId: string; versionId: string; data: FeedbackMessageInput },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminSendVersionFeedback>>,
  TError,
  { nodeId: string; versionId: string; data: FeedbackMessageInput },
  TContext
> => {
  const mutationKey = ['adminSendVersionFeedback']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminSendVersionFeedback>>,
    { nodeId: string; versionId: string; data: FeedbackMessageInput }
  > = (props) => {
    const { nodeId, versionId, data } = props ?? {}

    return adminSendVersionFeedback(nodeId, versionId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminSendVersionFeedbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminSendVersionFeedback>>
>
export type AdminSendVersionFeedbackMutationBody = FeedbackMessageInput
export type AdminSendVersionFeedbackMutationError = FeedbackError

/**
 * @summary Start or reply to a private version conversation
 */
export const useAdminSendVersionFeedback = <
  TError = FeedbackError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminSendVersionFeedback>>,
      TError,
      { nodeId: string; versionId: string; data: FeedbackMessageInput },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof adminSendVersionFeedback>>,
  TError,
  { nodeId: string; versionId: string; data: FeedbackMessageInput },
  TContext
> => {
  const mutationOptions = getAdminSendVersionFeedbackMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}

/**
 * GET requests have no read side effect. Advance last_read_message_seq only through messages actually consumed by this admin identity, with the current target. Repeating an acknowledgement never moves the read position backward.
 * @summary Acknowledge processed messages without replying
 */
export const adminReadVersionFeedback = (
  nodeId: string,
  versionId: string,
  feedbackReadInput: FeedbackReadInput,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<FeedbackReadResult>(
    {
      url: `/admin/nodes/${nodeId}/versions/${versionId}/feedback/read`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: feedbackReadInput,
      signal,
    },
    options
  )
}

export const getAdminReadVersionFeedbackMutationOptions = <
  TError = FeedbackError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminReadVersionFeedback>>,
    TError,
    { nodeId: string; versionId: string; data: FeedbackReadInput },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminReadVersionFeedback>>,
  TError,
  { nodeId: string; versionId: string; data: FeedbackReadInput },
  TContext
> => {
  const mutationKey = ['adminReadVersionFeedback']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminReadVersionFeedback>>,
    { nodeId: string; versionId: string; data: FeedbackReadInput }
  > = (props) => {
    const { nodeId, versionId, data } = props ?? {}

    return adminReadVersionFeedback(nodeId, versionId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminReadVersionFeedbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminReadVersionFeedback>>
>
export type AdminReadVersionFeedbackMutationBody = FeedbackReadInput
export type AdminReadVersionFeedbackMutationError = FeedbackError

/**
 * @summary Acknowledge processed messages without replying
 */
export const useAdminReadVersionFeedback = <
  TError = FeedbackError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminReadVersionFeedback>>,
      TError,
      { nodeId: string; versionId: string; data: FeedbackReadInput },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof adminReadVersionFeedback>>,
  TError,
  { nodeId: string; versionId: string; data: FeedbackReadInput },
  TContext
> => {
  const mutationOptions = getAdminReadVersionFeedbackMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}

/**
 * For active Registry admins using a Firebase ID token. Filter state by awaiting_admin, awaiting_author or resolved; combine nodeId and publisherId as needed. Omit state for all conversations. Returns up to 20 summaries, newest activity first with a stable ID tie-breaker. Follow the opaque next_cursor with the same filters until null. Versions without a conversation are available through adminListNodeVersions with feedback_status=unprocessed. Archived conversations can be present; read their permissions before writing.
 * @summary List private conversations by current state
 */
export const adminListVersionFeedback = (
  params?: AdminListVersionFeedbackParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<FeedbackInbox>(
    { url: `/admin/node-version-feedback`, method: 'GET', params, signal },
    options
  )
}

export const getAdminListVersionFeedbackQueryKey = (
  params?: AdminListVersionFeedbackParams
) => {
  return [`/admin/node-version-feedback`, ...(params ? [params] : [])] as const
}

export const getAdminListVersionFeedbackQueryOptions = <
  TData = Awaited<ReturnType<typeof adminListVersionFeedback>>,
  TError = FeedbackError,
>(
  params?: AdminListVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getAdminListVersionFeedbackQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminListVersionFeedback>>
  > = ({ signal }) => adminListVersionFeedback(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminListVersionFeedback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListVersionFeedbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminListVersionFeedback>>
>
export type AdminListVersionFeedbackQueryError = FeedbackError

export function useAdminListVersionFeedback<
  TData = Awaited<ReturnType<typeof adminListVersionFeedback>>,
  TError = FeedbackError,
>(
  params: undefined | AdminListVersionFeedbackParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListVersionFeedback>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListVersionFeedback>>,
          TError,
          Awaited<ReturnType<typeof adminListVersionFeedback>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminListVersionFeedback<
  TData = Awaited<ReturnType<typeof adminListVersionFeedback>>,
  TError = FeedbackError,
>(
  params?: AdminListVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListVersionFeedback>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListVersionFeedback>>,
          TError,
          Awaited<ReturnType<typeof adminListVersionFeedback>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminListVersionFeedback<
  TData = Awaited<ReturnType<typeof adminListVersionFeedback>>,
  TError = FeedbackError,
>(
  params?: AdminListVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List private conversations by current state
 */

export function useAdminListVersionFeedback<
  TData = Awaited<ReturnType<typeof adminListVersionFeedback>>,
  TError = FeedbackError,
>(
  params?: AdminListVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAdminListVersionFeedbackQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

export const authorGetVersionFeedback = (
  publisherId: string,
  nodeId: string,
  versionId: string,
  params?: AuthorGetVersionFeedbackParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<FeedbackResponse>(
    {
      url: `/publishers/${publisherId}/nodes/${nodeId}/versions/${versionId}/feedback`,
      method: 'GET',
      params,
      signal,
    },
    options
  )
}

export const getAuthorGetVersionFeedbackQueryKey = (
  publisherId?: string,
  nodeId?: string,
  versionId?: string,
  params?: AuthorGetVersionFeedbackParams
) => {
  return [
    `/publishers/${publisherId}/nodes/${nodeId}/versions/${versionId}/feedback`,
    ...(params ? [params] : []),
  ] as const
}

export const getAuthorGetVersionFeedbackQueryOptions = <
  TData = Awaited<ReturnType<typeof authorGetVersionFeedback>>,
  TError = FeedbackError,
>(
  publisherId: string,
  nodeId: string,
  versionId: string,
  params?: AuthorGetVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authorGetVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getAuthorGetVersionFeedbackQueryKey(publisherId, nodeId, versionId, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authorGetVersionFeedback>>
  > = ({ signal }) =>
    authorGetVersionFeedback(
      publisherId,
      nodeId,
      versionId,
      params,
      requestOptions,
      signal
    )

  return {
    queryKey,
    queryFn,
    enabled: !!(publisherId && nodeId && versionId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof authorGetVersionFeedback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthorGetVersionFeedbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof authorGetVersionFeedback>>
>
export type AuthorGetVersionFeedbackQueryError = FeedbackError

export function useAuthorGetVersionFeedback<
  TData = Awaited<ReturnType<typeof authorGetVersionFeedback>>,
  TError = FeedbackError,
>(
  publisherId: string,
  nodeId: string,
  versionId: string,
  params: undefined | AuthorGetVersionFeedbackParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authorGetVersionFeedback>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authorGetVersionFeedback>>,
          TError,
          Awaited<ReturnType<typeof authorGetVersionFeedback>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthorGetVersionFeedback<
  TData = Awaited<ReturnType<typeof authorGetVersionFeedback>>,
  TError = FeedbackError,
>(
  publisherId: string,
  nodeId: string,
  versionId: string,
  params?: AuthorGetVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authorGetVersionFeedback>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authorGetVersionFeedback>>,
          TError,
          Awaited<ReturnType<typeof authorGetVersionFeedback>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthorGetVersionFeedback<
  TData = Awaited<ReturnType<typeof authorGetVersionFeedback>>,
  TError = FeedbackError,
>(
  publisherId: string,
  nodeId: string,
  versionId: string,
  params?: AuthorGetVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authorGetVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useAuthorGetVersionFeedback<
  TData = Awaited<ReturnType<typeof authorGetVersionFeedback>>,
  TError = FeedbackError,
>(
  publisherId: string,
  nodeId: string,
  versionId: string,
  params?: AuthorGetVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authorGetVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAuthorGetVersionFeedbackQueryOptions(
    publisherId,
    nodeId,
    versionId,
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

export const authorSendVersionFeedback = (
  publisherId: string,
  nodeId: string,
  versionId: string,
  feedbackMessageInput: FeedbackMessageInput,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<FeedbackResponse>(
    {
      url: `/publishers/${publisherId}/nodes/${nodeId}/versions/${versionId}/feedback/messages`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: feedbackMessageInput,
      signal,
    },
    options
  )
}

export const getAuthorSendVersionFeedbackMutationOptions = <
  TError = FeedbackError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authorSendVersionFeedback>>,
    TError,
    {
      publisherId: string
      nodeId: string
      versionId: string
      data: FeedbackMessageInput
    },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authorSendVersionFeedback>>,
  TError,
  {
    publisherId: string
    nodeId: string
    versionId: string
    data: FeedbackMessageInput
  },
  TContext
> => {
  const mutationKey = ['authorSendVersionFeedback']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authorSendVersionFeedback>>,
    {
      publisherId: string
      nodeId: string
      versionId: string
      data: FeedbackMessageInput
    }
  > = (props) => {
    const { publisherId, nodeId, versionId, data } = props ?? {}

    return authorSendVersionFeedback(
      publisherId,
      nodeId,
      versionId,
      data,
      requestOptions
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthorSendVersionFeedbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof authorSendVersionFeedback>>
>
export type AuthorSendVersionFeedbackMutationBody = FeedbackMessageInput
export type AuthorSendVersionFeedbackMutationError = FeedbackError

export const useAuthorSendVersionFeedback = <
  TError = FeedbackError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authorSendVersionFeedback>>,
      TError,
      {
        publisherId: string
        nodeId: string
        versionId: string
        data: FeedbackMessageInput
      },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authorSendVersionFeedback>>,
  TError,
  {
    publisherId: string
    nodeId: string
    versionId: string
    data: FeedbackMessageInput
  },
  TContext
> => {
  const mutationOptions = getAuthorSendVersionFeedbackMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}

export const authorReadVersionFeedback = (
  publisherId: string,
  nodeId: string,
  versionId: string,
  feedbackReadInput: FeedbackReadInput,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<FeedbackReadResult>(
    {
      url: `/publishers/${publisherId}/nodes/${nodeId}/versions/${versionId}/feedback/read`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: feedbackReadInput,
      signal,
    },
    options
  )
}

export const getAuthorReadVersionFeedbackMutationOptions = <
  TError = FeedbackError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authorReadVersionFeedback>>,
    TError,
    {
      publisherId: string
      nodeId: string
      versionId: string
      data: FeedbackReadInput
    },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authorReadVersionFeedback>>,
  TError,
  {
    publisherId: string
    nodeId: string
    versionId: string
    data: FeedbackReadInput
  },
  TContext
> => {
  const mutationKey = ['authorReadVersionFeedback']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authorReadVersionFeedback>>,
    {
      publisherId: string
      nodeId: string
      versionId: string
      data: FeedbackReadInput
    }
  > = (props) => {
    const { publisherId, nodeId, versionId, data } = props ?? {}

    return authorReadVersionFeedback(
      publisherId,
      nodeId,
      versionId,
      data,
      requestOptions
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthorReadVersionFeedbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof authorReadVersionFeedback>>
>
export type AuthorReadVersionFeedbackMutationBody = FeedbackReadInput
export type AuthorReadVersionFeedbackMutationError = FeedbackError

export const useAuthorReadVersionFeedback = <
  TError = FeedbackError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authorReadVersionFeedback>>,
      TError,
      {
        publisherId: string
        nodeId: string
        versionId: string
        data: FeedbackReadInput
      },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authorReadVersionFeedback>>,
  TError,
  {
    publisherId: string
    nodeId: string
    versionId: string
    data: FeedbackReadInput
  },
  TContext
> => {
  const mutationOptions = getAuthorReadVersionFeedbackMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}

/**
 * Publisher owners only. versionId identifies the replacement. All selected versions must belong to the same node, precede the replacement by upload time, and have current non-archived feedback. Validates every target and revision atomically. This records an owner handoff, not approval or verification of a fix. Retry the identical request after a lost response; changed conversations return 409.
 * @summary Deprecate earlier versions and close their feedback in favor of this replacement version
 */
export const authorSupersedeVersionFeedback = (
  publisherId: string,
  nodeId: string,
  versionId: string,
  feedbackSupersedeInput: FeedbackSupersedeInput,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<null>(
    {
      url: `/publishers/${publisherId}/nodes/${nodeId}/versions/${versionId}/feedback/supersede`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: feedbackSupersedeInput,
      signal,
    },
    options
  )
}

export const getAuthorSupersedeVersionFeedbackMutationOptions = <
  TError = FeedbackError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authorSupersedeVersionFeedback>>,
    TError,
    {
      publisherId: string
      nodeId: string
      versionId: string
      data: FeedbackSupersedeInput
    },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authorSupersedeVersionFeedback>>,
  TError,
  {
    publisherId: string
    nodeId: string
    versionId: string
    data: FeedbackSupersedeInput
  },
  TContext
> => {
  const mutationKey = ['authorSupersedeVersionFeedback']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authorSupersedeVersionFeedback>>,
    {
      publisherId: string
      nodeId: string
      versionId: string
      data: FeedbackSupersedeInput
    }
  > = (props) => {
    const { publisherId, nodeId, versionId, data } = props ?? {}

    return authorSupersedeVersionFeedback(
      publisherId,
      nodeId,
      versionId,
      data,
      requestOptions
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthorSupersedeVersionFeedbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof authorSupersedeVersionFeedback>>
>
export type AuthorSupersedeVersionFeedbackMutationBody = FeedbackSupersedeInput
export type AuthorSupersedeVersionFeedbackMutationError = FeedbackError

/**
 * @summary Deprecate earlier versions and close their feedback in favor of this replacement version
 */
export const useAuthorSupersedeVersionFeedback = <
  TError = FeedbackError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authorSupersedeVersionFeedback>>,
      TError,
      {
        publisherId: string
        nodeId: string
        versionId: string
        data: FeedbackSupersedeInput
      },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authorSupersedeVersionFeedback>>,
  TError,
  {
    publisherId: string
    nodeId: string
    versionId: string
    data: FeedbackSupersedeInput
  },
  TContext
> => {
  const mutationOptions =
    getAuthorSupersedeVersionFeedbackMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}

export const authorListVersionFeedback = (
  params?: AuthorListVersionFeedbackParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<FeedbackInbox>(
    { url: `/users/me/node-version-feedback`, method: 'GET', params, signal },
    options
  )
}

export const getAuthorListVersionFeedbackQueryKey = (
  params?: AuthorListVersionFeedbackParams
) => {
  return [
    `/users/me/node-version-feedback`,
    ...(params ? [params] : []),
  ] as const
}

export const getAuthorListVersionFeedbackQueryOptions = <
  TData = Awaited<ReturnType<typeof authorListVersionFeedback>>,
  TError = FeedbackError,
>(
  params?: AuthorListVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authorListVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getAuthorListVersionFeedbackQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authorListVersionFeedback>>
  > = ({ signal }) => authorListVersionFeedback(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authorListVersionFeedback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthorListVersionFeedbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof authorListVersionFeedback>>
>
export type AuthorListVersionFeedbackQueryError = FeedbackError

export function useAuthorListVersionFeedback<
  TData = Awaited<ReturnType<typeof authorListVersionFeedback>>,
  TError = FeedbackError,
>(
  params: undefined | AuthorListVersionFeedbackParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authorListVersionFeedback>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authorListVersionFeedback>>,
          TError,
          Awaited<ReturnType<typeof authorListVersionFeedback>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthorListVersionFeedback<
  TData = Awaited<ReturnType<typeof authorListVersionFeedback>>,
  TError = FeedbackError,
>(
  params?: AuthorListVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authorListVersionFeedback>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authorListVersionFeedback>>,
          TError,
          Awaited<ReturnType<typeof authorListVersionFeedback>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthorListVersionFeedback<
  TData = Awaited<ReturnType<typeof authorListVersionFeedback>>,
  TError = FeedbackError,
>(
  params?: AuthorListVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authorListVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useAuthorListVersionFeedback<
  TData = Awaited<ReturnType<typeof authorListVersionFeedback>>,
  TError = FeedbackError,
>(
  params?: AuthorListVersionFeedbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authorListVersionFeedback>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAuthorListVersionFeedbackQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * For active Registry admins using a Firebase ID token. feedback_status classifies no messages, latest admin message or latest author message; it does not filter conversation resolution. Combine it with nodeId, statuses and status_reason. Filters apply before total counts and pagination. Results include private scan evidence and use creation time descending with an ID tie-breaker. Processing records can change queue membership: re-query page 1 or collect IDs before mutating, rather than advancing page numbers while removing items.
 * @summary List admin versions by moderation and feedback handling status
 */
export const adminListNodeVersions = (
  params?: AdminListNodeVersionsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<AdminVersionList>(
    { url: `/admin/nodeversions`, method: 'GET', params, signal },
    options
  )
}

export const getAdminListNodeVersionsQueryKey = (
  params?: AdminListNodeVersionsParams
) => {
  return [`/admin/nodeversions`, ...(params ? [params] : [])] as const
}

export const getAdminListNodeVersionsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminListNodeVersions>>,
  TError = FeedbackError,
>(
  params?: AdminListNodeVersionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListNodeVersions>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getAdminListNodeVersionsQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminListNodeVersions>>
  > = ({ signal }) => adminListNodeVersions(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminListNodeVersions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListNodeVersionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminListNodeVersions>>
>
export type AdminListNodeVersionsQueryError = FeedbackError

export function useAdminListNodeVersions<
  TData = Awaited<ReturnType<typeof adminListNodeVersions>>,
  TError = FeedbackError,
>(
  params: undefined | AdminListNodeVersionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListNodeVersions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListNodeVersions>>,
          TError,
          Awaited<ReturnType<typeof adminListNodeVersions>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminListNodeVersions<
  TData = Awaited<ReturnType<typeof adminListNodeVersions>>,
  TError = FeedbackError,
>(
  params?: AdminListNodeVersionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListNodeVersions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListNodeVersions>>,
          TError,
          Awaited<ReturnType<typeof adminListNodeVersions>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAdminListNodeVersions<
  TData = Awaited<ReturnType<typeof adminListNodeVersions>>,
  TError = FeedbackError,
>(
  params?: AdminListNodeVersionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListNodeVersions>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List admin versions by moderation and feedback handling status
 */

export function useAdminListNodeVersions<
  TData = Awaited<ReturnType<typeof adminListNodeVersions>>,
  TError = FeedbackError,
>(
  params?: AdminListNodeVersionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListNodeVersions>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAdminListNodeVersionsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}
