/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Drip API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import { customInstance } from './mutator/axios-instance';
export type LoadWorkspaceSnapshot200 = {
  /** A message confirming the workspace snapshot was loaded */
  message?: string;
};

export type LoadWorkspaceSnapshotBody = {
  /** The unique identifier for the workspace snapshot */
  workspaceSnapshotId?: string;
};

export type CreateWorkspaceSnapshot201 = {
  /** The unique identifier for the workspace snapshot */
  workspaceSnapshotId?: string;
};

export type CreateWorkspaceSnapshotBody = {
  /** A description of the workspace snapshot */
  description?: string;
  /** The unique identifier for the workspace */
  workspaceId?: string;
};

export type CreateDefaultWorkspace201 = {
  /** The unique identifier for the default workspace */
  workspaceId?: string;
};

export type UpdateWorkspace200 = {
  /** The unique identifier for the workspace */
  workspaceId?: string;
};

export type UpdateWorkspaceBody = {
  workflow?: Workflow;
  /** The unique identifier for the workspace */
  workspaceId?: string;
};

export type CreateWorkspace201 = {
  /** The unique identifier for the workspace */
  workspaceId?: string;
};

export type CreateWorkspaceBody = {
  /** The name of the workspace */
  name?: string;
};

export type GetWorkspaces200 = {
  workspaces?: Workspace[];
};

export type GetWorkspacesParams = {
limit?: number;
offset?: number;
};

export type CancelWorkflowJob200 = {
  /** A message confirming the cancellation request */
  message?: string;
};

export type UpdateWorkflowJobBody = {
  /** The updated list of output URLs generated by the workflow job */
  outputUrls?: string[];
  status?: WorkflowJobStatus;
};

export type CreateWorkflowJobBody = {
  /** The webhook will be called when the status of the job changes */
  webhookUrl: string;
};

export type GetWorkflow200AllOf = {
  authorId?: string;
  sessionId?: string;
};

export type GetWorkflow200 = Workflow & GetWorkflow200AllOf;

export type CreateWorkflowBody = {
  /** The JSON file content of the workflow. */
  fileContent: string;
  /** User-defined name for the workflow */
  name: string;
};

export type GetUserWorkflows200 = {
  workflows?: Workflow[];
};

export type GetUserWorkflowsParams = {
limit?: number;
offset?: number;
};

export type PostValidateTokenBody = {
  /** The access token to be validated. */
  token: string;
};

export type UpdateSessionBody = {
  /** The number of GPUs attached to this session. Can be 0 or 1. */
  gpuCount?: number;
  gpuType?: GPUType;
  /** Whether to update the end time of the session to 30 minutes from now. */
  updateEndTime?: boolean;
};

export type CreateSessionBody = {
  'gpu-type'?: GPUType;
};

export type GetSessions200 = {
  sessions?: Session[];
};

export type GetSessionsParams = {
/**
 * Filter sessions by status
 */
status?: SessionStatus;
};

export type PostUploadArtifact200 = {
  message?: string;
};

export type PostUploadArtifactBody = {
  branch_name: string;
  /** The name of the bucket where the output files are stored */
  bucket_name?: string;
  /** The path to ComfyUI logs. eg. gs://bucket-name/logs */
  comfy_logs_gcs_path?: string;
  commit_hash: string;
  /** Cuda version. */
  cuda_version?: string;
  /** Unique identifier for the job */
  job_id: string;
  /** Operating system used in the run */
  os: string;
  /** A comma separated string that contains GCS path(s) to output files. eg. gs://bucket-name/output, gs://bucket-name/output2 */
  output_files_gcs_paths?: string;
  /** Repository name */
  repo: string;
  /** Unique identifier for the run */
  run_id: string;
  /** The name of the workflow */
  workflow_name: string;
};

export type GetGitcommit200 = {
  jobResults?: ActionJobResult[];
  totalNumberOfPages?: number;
};

export type GetGitcommitParams = {
/**
 * The ID of the commit to fetch data for.
 */
commitId?: string;
/**
 * The operating system to filter the CI data by.
 */
operatingSystem?: string;
/**
 * The name of the workflow to filter the CI data by.
 */
workflowName?: string;
/**
 * The page number to retrieve.
 */
page?: number;
/**
 * The number of items to include per page.
 */
pageSize?: number;
};

export interface Workspace {
  /** The unique id for this workspace. */
  id?: string;
  machine?: Machine;
  /** The name of the workspace. */
  name?: string;
  workflow?: Workflow;
}

/**
 * The status of the workflow being executed:
- `queued` - The job is in queue and will be executed soon.
- `started` - The job has started executing.
- `failed` - The job has failed.
- `succeeded` - The job has finished successfully.

 */
export type WorkflowJobStatus = typeof WorkflowJobStatus[keyof typeof WorkflowJobStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkflowJobStatus = {
  queued: 'queued',
  started: 'started',
  failed: 'failed',
  succeeded: 'succeeded',
} as const;

export interface WorkflowJob {
  id?: string;
  /** A list of URLs to the output generated by the workflow job. */
  outputUrls?: string[];
  status?: WorkflowJobStatus;
  /** This webhook will be called when the status of the job changes */
  webhookUrl?: string;
}

export interface Workflow {
  /** The unique id for this workflow. */
  id?: string;
  /** The date and time the workflow was last updated. */
  updatedAt?: string;
  /** The JSON representation of the workflow. */
  workflowJSON?: string;
  /** Name of the workflow */
  workflowName?: string;
}

export interface User {
  /** The email address for this user. */
  email?: string;
  /** The unique id for this user. */
  id?: string;
  /** Indicates if the user has admin privileges. */
  isAdmin?: boolean;
  /** Indicates if the user is approved. */
  isApproved?: boolean;
  /** The name for this user. */
  name?: string;
}

export interface StorageFile {
  /** Path to the file in storage */
  file_path?: string;
  /** Unique identifier for the storage file */
  id?: string;
  /** Public URL */
  public_url?: string;
}

/**
 * The status of the workflow being executed:
- `active` - The session is active and can be used.
- `inactive` - The session is inactive and cannot be used.

 */
export type SessionStatus = typeof SessionStatus[keyof typeof SessionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;

export type MachineType = typeof MachineType[keyof typeof MachineType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MachineType = {
  'n1-standard-1': 'n1-standard-1',
  'n1-standard-2': 'n1-standard-2',
  'n1-standard-4': 'n1-standard-4',
  'n1-standard-8': 'n1-standard-8',
  'n1-standard-16': 'n1-standard-16',
  'n1-standard-32': 'n1-standard-32',
  'n1-standard-64': 'n1-standard-64',
  'n1-standard-96': 'n1-standard-96',
  'a2-highgpu-1g': 'a2-highgpu-1g',
  'a2-highgpu-2g': 'a2-highgpu-2g',
  'a2-highgpu-4g': 'a2-highgpu-4g',
  'a2-highgpu-8g': 'a2-highgpu-8g',
  'a2-megagpu-16g': 'a2-megagpu-16g',
  'a2-ultragpu-1g': 'a2-ultragpu-1g',
  'a2-ultragpu-2g': 'a2-ultragpu-2g',
  'a2-ultragpu-4g': 'a2-ultragpu-4g',
  'a2-ultragpu-8g': 'a2-ultragpu-8g',
  'a3-highgpu-8g': 'a3-highgpu-8g',
  'g2-standard-4': 'g2-standard-4',
  'g2-standard-8': 'g2-standard-8',
  'g2-standard-12': 'g2-standard-12',
  'g2-standard-16': 'g2-standard-16',
  'g2-standard-24': 'g2-standard-24',
  'g2-standard-32': 'g2-standard-32',
  'g2-standard-48': 'g2-standard-48',
  'g2-standard-96': 'g2-standard-96',
} as const;

export type GPUType = typeof GPUType[keyof typeof GPUType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPUType = {
  'nvidia-h100-80gb': 'nvidia-h100-80gb',
  'nvidia-l4': 'nvidia-l4',
  'nvidia-tesla-a100': 'nvidia-tesla-a100',
  'nvidia-a100-80gb': 'nvidia-a100-80gb',
  'nvidia-tesla-t4': 'nvidia-tesla-t4',
  'nvidia-tesla-v100': 'nvidia-tesla-v100',
  'nvidia-tesla-p100': 'nvidia-tesla-p100',
  'nvidia-tesla-p4': 'nvidia-tesla-p4',
} as const;

export interface Session {
  /** [Output only] The number of GPUs attached to this session. */
  gpuCount?: number;
  gpuType?: GPUType;
  id?: string;
  machineType?: MachineType;
  /** This url to interface with this session. */
  publicUrl?: string;
  /** [Output only] The storage capacity of the session. */
  storage?: string;
}

export interface Machine {
  /** The number of GPUs attached to this machine. */
  gpuCount?: number;
  gpuType?: GPUType;
  /** The unique id for this machine. */
  id?: string;
  machineType?: MachineType;
}

export interface ErrorResponse {
  error: string;
  message: string;
}

export interface ActionJobResult {
  /** Identifier of the run this result belongs to */
  action_run_id?: string;
  /** The hash of the commit */
  commit_hash?: string;
  /** The ID of the commit */
  commit_id?: string;
  /** The repository name */
  git_repo?: string;
  /** GPU type used */
  gpu_type?: string;
  /** Unique identifier for the job result */
  id?: string;
  /** Operating system used */
  operating_system?: string;
  /** PyTorch version used */
  pytorch_version?: string;
  storage_file?: StorageFile;
  /** Name of the workflow */
  workflow_name?: string;
}




// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;


/**
 * Returns all runs, jobs, job results, and storage files associated with a given commit.
 * @summary Retrieve CI data for a given commit
 */
export const getGitcommit = (
    params?: GetGitcommitParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetGitcommit200>(
      {url: `/gitcommit`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetGitcommitQueryKey = (params?: GetGitcommitParams,) => {
    return [`/gitcommit`, ...(params ? [params]: [])] as const;
    }

    
export const getGetGitcommitQueryOptions = <TData = Awaited<ReturnType<typeof getGitcommit>>, TError = void>(params?: GetGitcommitParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGitcommit>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGitcommitQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGitcommit>>> = ({ signal }) => getGitcommit(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGitcommit>>, TError, TData> & { queryKey: QueryKey }
}

export type GetGitcommitQueryResult = NonNullable<Awaited<ReturnType<typeof getGitcommit>>>
export type GetGitcommitQueryError = void

/**
 * @summary Retrieve CI data for a given commit
 */
export const useGetGitcommit = <TData = Awaited<ReturnType<typeof getGitcommit>>, TError = void>(
 params?: GetGitcommitParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGitcommit>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetGitcommitQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Receive artifacts (output files) from the ComfyUI GitHub Action
 */
export const postUploadArtifact = (
    postUploadArtifactBody: PostUploadArtifactBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PostUploadArtifact200>(
      {url: `/upload-artifact`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postUploadArtifactBody
    },
      options);
    }
  


export const getPostUploadArtifactMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUploadArtifact>>, TError,{data: PostUploadArtifactBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postUploadArtifact>>, TError,{data: PostUploadArtifactBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUploadArtifact>>, {data: PostUploadArtifactBody}> = (props) => {
          const {data} = props ?? {};

          return  postUploadArtifact(data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type PostUploadArtifactMutationResult = NonNullable<Awaited<ReturnType<typeof postUploadArtifact>>>
    export type PostUploadArtifactMutationBody = PostUploadArtifactBody
    export type PostUploadArtifactMutationError = void

    /**
 * @summary Receive artifacts (output files) from the ComfyUI GitHub Action
 */
export const usePostUploadArtifact = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUploadArtifact>>, TError,{data: PostUploadArtifactBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getPostUploadArtifactMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get information about the calling user.
 */
export const getUser = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<User>(
      {url: `/users`, method: 'GET', signal
    },
      options);
    }
  

export const getGetUserQueryKey = () => {
    return [`/users`] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = void

/**
 * @summary Get information about the calling user.
 */
export const useGetUser = <TData = Awaited<ReturnType<typeof getUser>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetUserQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Stop sessions that have no active usage.
 */
export const stopExpiredSessions = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Session>(
      {url: `/users/sessions`, method: 'DELETE'
    },
      options);
    }
  


export const getStopExpiredSessionsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stopExpiredSessions>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof stopExpiredSessions>>, TError,void, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stopExpiredSessions>>, void> = () => {
          

          return  stopExpiredSessions(requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type StopExpiredSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof stopExpiredSessions>>>
    
    export type StopExpiredSessionsMutationError = void

    /**
 * @summary Stop sessions that have no active usage.
 */
export const useStopExpiredSessions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stopExpiredSessions>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getStopExpiredSessionsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get information about the calling user's session.
 */
export const getSessions = (
    params?: GetSessionsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSessions200>(
      {url: `/users/sessions`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetSessionsQueryKey = (params?: GetSessionsParams,) => {
    return [`/users/sessions`, ...(params ? [params]: [])] as const;
    }

    
export const getGetSessionsQueryOptions = <TData = Awaited<ReturnType<typeof getSessions>>, TError = void>(params?: GetSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSessions>>> = ({ signal }) => getSessions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getSessions>>>
export type GetSessionsQueryError = void

/**
 * @summary Get information about the calling user's session.
 */
export const useGetSessions = <TData = Awaited<ReturnType<typeof getSessions>>, TError = void>(
 params?: GetSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetSessionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a new session for a user. If an existing session is active (not deleted), it will be returned.
 */
export const createSession = (
    createSessionBody: CreateSessionBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Session>(
      {url: `/users/sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSessionBody
    },
      options);
    }
  


export const getCreateSessionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSession>>, {data: CreateSessionBody}> = (props) => {
          const {data} = props ?? {};

          return  createSession(data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type CreateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof createSession>>>
    export type CreateSessionMutationBody = CreateSessionBody
    export type CreateSessionMutationError = void

    /**
 * @summary Create a new session for a user. If an existing session is active (not deleted), it will be returned.
 */
export const useCreateSession = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getCreateSessionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get a specific session by its ID.
 */
export const getSession = (
    sessionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Session>(
      {url: `/users/sessions/${sessionId}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetSessionQueryKey = (sessionId: string,) => {
    return [`/users/sessions/${sessionId}`] as const;
    }

    
export const getGetSessionQueryOptions = <TData = Awaited<ReturnType<typeof getSession>>, TError = void>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionQueryKey(sessionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({ signal }) => getSession(sessionId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getSession>>>
export type GetSessionQueryError = void

/**
 * @summary Get a specific session by its ID.
 */
export const useGetSession = <TData = Awaited<ReturnType<typeof getSession>>, TError = void>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetSessionQueryOptions(sessionId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update a session by its ID.
 */
export const updateSession = (
    sessionId: string,
    updateSessionBody: UpdateSessionBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Session>(
      {url: `/users/sessions/${sessionId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateSessionBody
    },
      options);
    }
  


export const getUpdateSessionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSession>>, TError,{sessionId: string;data: UpdateSessionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSession>>, TError,{sessionId: string;data: UpdateSessionBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSession>>, {sessionId: string;data: UpdateSessionBody}> = (props) => {
          const {sessionId,data} = props ?? {};

          return  updateSession(sessionId,data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type UpdateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof updateSession>>>
    export type UpdateSessionMutationBody = UpdateSessionBody
    export type UpdateSessionMutationError = void

    /**
 * @summary Update a session by its ID.
 */
export const useUpdateSession = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSession>>, TError,{sessionId: string;data: UpdateSessionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getUpdateSessionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * Validates the provided access token and returns a session ID if valid.
 * @summary Validate an access token
 */
export const postValidateToken = (
    postValidateTokenBody: PostValidateTokenBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Session>(
      {url: `/validateToken`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postValidateTokenBody
    },
      options);
    }
  


export const getPostValidateTokenMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postValidateToken>>, TError,{data: PostValidateTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postValidateToken>>, TError,{data: PostValidateTokenBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postValidateToken>>, {data: PostValidateTokenBody}> = (props) => {
          const {data} = props ?? {};

          return  postValidateToken(data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type PostValidateTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postValidateToken>>>
    export type PostValidateTokenMutationBody = PostValidateTokenBody
    export type PostValidateTokenMutationError = void

    /**
 * @summary Validate an access token
 */
export const usePostValidateToken = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postValidateToken>>, TError,{data: PostValidateTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getPostValidateTokenMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get all workflows
 */
export const getUserWorkflows = (
    params?: GetUserWorkflowsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserWorkflows200>(
      {url: `/workflows`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetUserWorkflowsQueryKey = (params?: GetUserWorkflowsParams,) => {
    return [`/workflows`, ...(params ? [params]: [])] as const;
    }

    
export const getGetUserWorkflowsQueryOptions = <TData = Awaited<ReturnType<typeof getUserWorkflows>>, TError = unknown>(params?: GetUserWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserWorkflows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserWorkflowsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserWorkflows>>> = ({ signal }) => getUserWorkflows(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserWorkflows>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserWorkflowsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserWorkflows>>>
export type GetUserWorkflowsQueryError = unknown

/**
 * @summary Get all workflows
 */
export const useGetUserWorkflows = <TData = Awaited<ReturnType<typeof getUserWorkflows>>, TError = unknown>(
 params?: GetUserWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserWorkflows>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetUserWorkflowsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a new workflow
 */
export const createWorkflow = (
    createWorkflowBody: CreateWorkflowBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Workflow>(
      {url: `/workflows`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkflowBody
    },
      options);
    }
  


export const getCreateWorkflowMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkflow>>, TError,{data: CreateWorkflowBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createWorkflow>>, TError,{data: CreateWorkflowBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorkflow>>, {data: CreateWorkflowBody}> = (props) => {
          const {data} = props ?? {};

          return  createWorkflow(data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type CreateWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkflow>>>
    export type CreateWorkflowMutationBody = CreateWorkflowBody
    export type CreateWorkflowMutationError = void

    /**
 * @summary Create a new workflow
 */
export const useCreateWorkflow = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkflow>>, TError,{data: CreateWorkflowBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getCreateWorkflowMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Delete a workflow
 */
export const deleteWorkflow = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/workflows/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteWorkflowMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkflow>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkflow>>, TError,{id: string}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkflow>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteWorkflow(id,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkflow>>>
    
    export type DeleteWorkflowMutationError = unknown

    /**
 * @summary Delete a workflow
 */
export const useDeleteWorkflow = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkflow>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getDeleteWorkflowMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get a workflow
 */
export const getWorkflow = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetWorkflow200>(
      {url: `/workflows/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetWorkflowQueryKey = (id: string,) => {
    return [`/workflows/${id}`] as const;
    }

    
export const getGetWorkflowQueryOptions = <TData = Awaited<ReturnType<typeof getWorkflow>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkflowQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkflow>>> = ({ signal }) => getWorkflow(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkflow>>, TError, TData> & { queryKey: QueryKey }
}

export type GetWorkflowQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkflow>>>
export type GetWorkflowQueryError = void

/**
 * @summary Get a workflow
 */
export const useGetWorkflow = <TData = Awaited<ReturnType<typeof getWorkflow>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetWorkflowQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update an existing workflow
 */
export const updateWorkflow = (
    id: string,
    workflow: Workflow,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Workflow>(
      {url: `/workflows/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: workflow
    },
      options);
    }
  


export const getUpdateWorkflowMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkflow>>, TError,{id: string;data: Workflow}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateWorkflow>>, TError,{id: string;data: Workflow}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWorkflow>>, {id: string;data: Workflow}> = (props) => {
          const {id,data} = props ?? {};

          return  updateWorkflow(id,data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type UpdateWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof updateWorkflow>>>
    export type UpdateWorkflowMutationBody = Workflow
    export type UpdateWorkflowMutationError = void

    /**
 * @summary Update an existing workflow
 */
export const useUpdateWorkflow = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkflow>>, TError,{id: string;data: Workflow}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getUpdateWorkflowMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Create a new job for a specific workflow
 */
export const createWorkflowJob = (
    workflowId: string,
    createWorkflowJobBody: CreateWorkflowJobBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<WorkflowJob>(
      {url: `/workflows/${workflowId}/jobs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkflowJobBody
    },
      options);
    }
  


export const getCreateWorkflowJobMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkflowJob>>, TError,{workflowId: string;data: CreateWorkflowJobBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createWorkflowJob>>, TError,{workflowId: string;data: CreateWorkflowJobBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorkflowJob>>, {workflowId: string;data: CreateWorkflowJobBody}> = (props) => {
          const {workflowId,data} = props ?? {};

          return  createWorkflowJob(workflowId,data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type CreateWorkflowJobMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkflowJob>>>
    export type CreateWorkflowJobMutationBody = CreateWorkflowJobBody
    export type CreateWorkflowJobMutationError = void

    /**
 * @summary Create a new job for a specific workflow
 */
export const useCreateWorkflowJob = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkflowJob>>, TError,{workflowId: string;data: CreateWorkflowJobBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getCreateWorkflowJobMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get a job by ID for a specific workflow
 */
export const getWorkflowJob = (
    workflowId: string,
    jobId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<WorkflowJob>(
      {url: `/workflows/${workflowId}/jobs/${jobId}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetWorkflowJobQueryKey = (workflowId: string,
    jobId: string,) => {
    return [`/workflows/${workflowId}/jobs/${jobId}`] as const;
    }

    
export const getGetWorkflowJobQueryOptions = <TData = Awaited<ReturnType<typeof getWorkflowJob>>, TError = void>(workflowId: string,
    jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowJob>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkflowJobQueryKey(workflowId,jobId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkflowJob>>> = ({ signal }) => getWorkflowJob(workflowId,jobId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workflowId && jobId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkflowJob>>, TError, TData> & { queryKey: QueryKey }
}

export type GetWorkflowJobQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkflowJob>>>
export type GetWorkflowJobQueryError = void

/**
 * @summary Get a job by ID for a specific workflow
 */
export const useGetWorkflowJob = <TData = Awaited<ReturnType<typeof getWorkflowJob>>, TError = void>(
 workflowId: string,
    jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowJob>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetWorkflowJobQueryOptions(workflowId,jobId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update a job's status and output URLs for a specific workflow
 */
export const updateWorkflowJob = (
    workflowId: string,
    jobId: string,
    updateWorkflowJobBody: UpdateWorkflowJobBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<WorkflowJob>(
      {url: `/workflows/${workflowId}/jobs/${jobId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkflowJobBody
    },
      options);
    }
  


export const getUpdateWorkflowJobMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkflowJob>>, TError,{workflowId: string;jobId: string;data: UpdateWorkflowJobBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateWorkflowJob>>, TError,{workflowId: string;jobId: string;data: UpdateWorkflowJobBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWorkflowJob>>, {workflowId: string;jobId: string;data: UpdateWorkflowJobBody}> = (props) => {
          const {workflowId,jobId,data} = props ?? {};

          return  updateWorkflowJob(workflowId,jobId,data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type UpdateWorkflowJobMutationResult = NonNullable<Awaited<ReturnType<typeof updateWorkflowJob>>>
    export type UpdateWorkflowJobMutationBody = UpdateWorkflowJobBody
    export type UpdateWorkflowJobMutationError = ErrorResponse

    /**
 * @summary Update a job's status and output URLs for a specific workflow
 */
export const useUpdateWorkflowJob = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkflowJob>>, TError,{workflowId: string;jobId: string;data: UpdateWorkflowJobBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getUpdateWorkflowJobMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Cancel a specific job for a workflow
 */
export const cancelWorkflowJob = (
    workflowId: string,
    jobId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<CancelWorkflowJob200>(
      {url: `/workflows/${workflowId}/jobs/${jobId}/cancel`, method: 'POST'
    },
      options);
    }
  


export const getCancelWorkflowJobMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelWorkflowJob>>, TError,{workflowId: string;jobId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelWorkflowJob>>, TError,{workflowId: string;jobId: string}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelWorkflowJob>>, {workflowId: string;jobId: string}> = (props) => {
          const {workflowId,jobId} = props ?? {};

          return  cancelWorkflowJob(workflowId,jobId,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type CancelWorkflowJobMutationResult = NonNullable<Awaited<ReturnType<typeof cancelWorkflowJob>>>
    
    export type CancelWorkflowJobMutationError = void

    /**
 * @summary Cancel a specific job for a workflow
 */
export const useCancelWorkflowJob = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelWorkflowJob>>, TError,{workflowId: string;jobId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getCancelWorkflowJobMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get all workspaces for the user
 */
export const getWorkspaces = (
    params?: GetWorkspacesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetWorkspaces200>(
      {url: `/workspace`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetWorkspacesQueryKey = (params?: GetWorkspacesParams,) => {
    return [`/workspace`, ...(params ? [params]: [])] as const;
    }

    
export const getGetWorkspacesQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspaces>>, TError = void>(params?: GetWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspacesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspaces>>> = ({ signal }) => getWorkspaces(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspaces>>, TError, TData> & { queryKey: QueryKey }
}

export type GetWorkspacesQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaces>>>
export type GetWorkspacesQueryError = void

/**
 * @summary Get all workspaces for the user
 */
export const useGetWorkspaces = <TData = Awaited<ReturnType<typeof getWorkspaces>>, TError = void>(
 params?: GetWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetWorkspacesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a new workspace
 */
export const createWorkspace = (
    createWorkspaceBody: CreateWorkspaceBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<CreateWorkspace201>(
      {url: `/workspace`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkspaceBody
    },
      options);
    }
  


export const getCreateWorkspaceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkspace>>, TError,{data: CreateWorkspaceBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createWorkspace>>, TError,{data: CreateWorkspaceBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorkspace>>, {data: CreateWorkspaceBody}> = (props) => {
          const {data} = props ?? {};

          return  createWorkspace(data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type CreateWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkspace>>>
    export type CreateWorkspaceMutationBody = CreateWorkspaceBody
    export type CreateWorkspaceMutationError = void

    /**
 * @summary Create a new workspace
 */
export const useCreateWorkspace = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkspace>>, TError,{data: CreateWorkspaceBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getCreateWorkspaceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Update the workspace with the workflow content
 */
export const updateWorkspace = (
    updateWorkspaceBody: UpdateWorkspaceBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateWorkspace200>(
      {url: `/workspace`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkspaceBody
    },
      options);
    }
  


export const getUpdateWorkspaceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkspace>>, TError,{data: UpdateWorkspaceBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateWorkspace>>, TError,{data: UpdateWorkspaceBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWorkspace>>, {data: UpdateWorkspaceBody}> = (props) => {
          const {data} = props ?? {};

          return  updateWorkspace(data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type UpdateWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof updateWorkspace>>>
    export type UpdateWorkspaceMutationBody = UpdateWorkspaceBody
    export type UpdateWorkspaceMutationError = void

    /**
 * @summary Update the workspace with the workflow content
 */
export const useUpdateWorkspace = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkspace>>, TError,{data: UpdateWorkspaceBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getUpdateWorkspaceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Create the default workspace. It retrieves the default workspace if it already exists.
 */
export const createDefaultWorkspace = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<CreateDefaultWorkspace201>(
      {url: `/workspace/default`, method: 'POST'
    },
      options);
    }
  


export const getCreateDefaultWorkspaceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDefaultWorkspace>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDefaultWorkspace>>, TError,void, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDefaultWorkspace>>, void> = () => {
          

          return  createDefaultWorkspace(requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type CreateDefaultWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof createDefaultWorkspace>>>
    
    export type CreateDefaultWorkspaceMutationError = void

    /**
 * @summary Create the default workspace. It retrieves the default workspace if it already exists.
 */
export const useCreateDefaultWorkspace = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDefaultWorkspace>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getCreateDefaultWorkspaceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Create a snapshot of the current workspace
 */
export const createWorkspaceSnapshot = (
    createWorkspaceSnapshotBody: CreateWorkspaceSnapshotBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<CreateWorkspaceSnapshot201>(
      {url: `/workspace/snapshot/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkspaceSnapshotBody
    },
      options);
    }
  


export const getCreateWorkspaceSnapshotMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkspaceSnapshot>>, TError,{data: CreateWorkspaceSnapshotBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createWorkspaceSnapshot>>, TError,{data: CreateWorkspaceSnapshotBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorkspaceSnapshot>>, {data: CreateWorkspaceSnapshotBody}> = (props) => {
          const {data} = props ?? {};

          return  createWorkspaceSnapshot(data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type CreateWorkspaceSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkspaceSnapshot>>>
    export type CreateWorkspaceSnapshotMutationBody = CreateWorkspaceSnapshotBody
    export type CreateWorkspaceSnapshotMutationError = void

    /**
 * @summary Create a snapshot of the current workspace
 */
export const useCreateWorkspaceSnapshot = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkspaceSnapshot>>, TError,{data: CreateWorkspaceSnapshotBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getCreateWorkspaceSnapshotMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Load a workspace snapshot
 */
export const loadWorkspaceSnapshot = (
    loadWorkspaceSnapshotBody: LoadWorkspaceSnapshotBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<LoadWorkspaceSnapshot200>(
      {url: `/workspace/snapshot/load/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loadWorkspaceSnapshotBody
    },
      options);
    }
  


export const getLoadWorkspaceSnapshotMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loadWorkspaceSnapshot>>, TError,{data: LoadWorkspaceSnapshotBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loadWorkspaceSnapshot>>, TError,{data: LoadWorkspaceSnapshotBody}, TContext> => {
 const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loadWorkspaceSnapshot>>, {data: LoadWorkspaceSnapshotBody}> = (props) => {
          const {data} = props ?? {};

          return  loadWorkspaceSnapshot(data,requestOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type LoadWorkspaceSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof loadWorkspaceSnapshot>>>
    export type LoadWorkspaceSnapshotMutationBody = LoadWorkspaceSnapshotBody
    export type LoadWorkspaceSnapshotMutationError = void

    /**
 * @summary Load a workspace snapshot
 */
export const useLoadWorkspaceSnapshot = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loadWorkspaceSnapshot>>, TError,{data: LoadWorkspaceSnapshotBody}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {

      const mutationOptions = getLoadWorkspaceSnapshotMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
