name: Prettier on NativeApp PR

on:
    push:
        branches:
            - main
        paths:
            - NativeApp/**
    pull_request:
        branches:
            - main
            - production
            - staging
        paths:
            - NativeApp/**

jobs:
    prettier-native-app:
        runs-on: ubuntu-latest
        env:
            working-directory: ./NativeApp
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}
                  # This is important to fetch the changes to the previous commit
                  fetch-depth: 0

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  # This part is also where you can pass other options, for example:
                  prettier_options: --write **/*.{js,jsx,md,ts,tsx}
                  only_changed: True
