name: Next.js CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, staging, main]

jobs:
  build:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the prettier changed files back to the repository.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install bun
        run: npm install -g bun
      - name: Install Dependencies
        run: bun install
        env:
          HUSKY: 0
      - name: Run Next.js Lint
        run: bun fix
      - name: Run Format
        run: bun fmt
      - name: Scan i18n Keys
        run: bun scripts/scan-i18n.ts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Sort package.json
        run: bunx sort-package-json
      - name: Build the Next.js Project
        run: bun run build
      # commit prettier fixed code only if there are changes
      - name: Check for changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.verify_diff.outputs.changed == 'true'
        with:
          commit_message: "format: Apply prettier --fix changes"
          commit_options: "--no-verify"
        env:
          HUSKY: 0
