name: Next.js CI

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev, staging, main]

jobs:
    build:
        permissions:
          # Give the default GITHUB_TOKEN write permission to commit and push the prettier changed files back to the repository.
          contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Install Dependencies
              run: pnpm install
            - name: Run Next.js Lint
              run: pnpm run lint
            - name: Check Formatting with Prettier
              run: npx prettier --fix .
            - name: Build the Next.js Project
              run: pnpm run build
            # commit prettier fixed code
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "format: Apply prettier --fix changes"
