name: Chromatic Visual Testing

on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          package-manager-cache: false
          node-version: "22"
      - run: npm i -g bun
      - run: bun i
      - run: bun run test
